blank_issues_enabled: false
contact_links:
  - name: Contributing to pybacker
    url: https://github.com/YisusChrist/pybacker/blob/main/CONTRIBUTING.md
    about: Guidelines for how to report an issue.
  - name: Support
    url: https://github.com/YisusChrist/pybacker/discussions
    about: Ask the community for support
  - name: Documentation
    url: https://github.com/YisusChrist/pybacker/wiki
    about: Many questions might be already answered here.
